### ISSUE TITLE
Could you please provide the dataset for train?

### ISSUE THREAD

**Issue by Albert-Ye** [RichardYang40148/MidiNet#1]

**Comment by RichardYang40148** [comment]
Hi Albert,
I’m sorry that due to the copy right issue, I could not release the parsed dataset(the TheoryTabs). However, for training with the open source data, I recommend to look into the Lakh MIDI Dataset:
http://colinraffel.com/projects/lmd/
As for the preprocessing strategy and tools, you can check out the pretty midi toolbox:
https://github.com/craffel/pretty-midi
Also I encourage anyone who is trying to train MidiNet by using bigger dataset or real world data, please check out the follow up research of MidiNet, the MuseGAN to gain more insight:
https://salu133445.github.io/musegan/

**Comment by Albert-Ye** [comment]
OK，thank you!
