### ISSUE TITLE
a request of the code to convert midi to npy

### ISSUE THREAD

**Issue by zzdang** [RichardYang40148/MidiNet#4]
hi,I read the musegan' code ,it isn't complete ,I'm confusing about the process to convert midi data to your train data.
Would you like to sharing you code of converting midi data?
Thanks a lot !

**Comment by RichardYang40148** [comment]
I think my colleagues just released the data processing code recently.
https://salu133445.github.io/pypianoroll/getting_started.html

By the way, if you are looking for training MidiNet only instead of musegan, you can also use pretty_midi(http://craffel.github.io/pretty-midi/) to process MIDI into piano roll, and either downsample the time resolution into what you want(16 for a bar in the MidiNet paper), or apply your own process steps which you think is logical.

**Comment by zzdang** [comment]
tks,I got some *.npz files using the preprocessing code in musegan,but midinet needs some npy file ,eg. octave2_x.npy. What can I do to convert the *.npz files to your train data?

**Comment by RichardYang40148** [comment]
The *.npz is the compressed format of numpy array. You can check out the numpy.load instructions.

**Comment by Atralb** [comment]
@RichardYang40148  Hi, the link isn't right anymore. I've looked at the repo you were referring to, but I can't see where the preprocessing part is now. Do you know ?

**Comment by RichardYang40148** [comment]
Hi, the author has wrapped up the preprocessing code as a python toolbox, please check out
https://salu133445.github.io/pypianoroll/getting_started.html
